# Generated by Django 5.1.15 on 2026-06-23 20:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
