# Generated by Django 5.1.15 on 2026-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_subscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
